// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: pkg/ODXT/proto/odxt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XSet          map[string]int64       `protobuf:"bytes,1,rep,name=x_set,json=xSet,proto3" json:"x_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TSet          map[string]*TsetValue  `protobuf:"bytes,2,rep,name=t_set,json=tSet,proto3" json:"t_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ODXT_proto_odxt_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetXSet() map[string]int64 {
	if x != nil {
		return x.XSet
	}
	return nil
}

func (x *UpdateRequest) GetTSet() map[string]*TsetValue {
	if x != nil {
		return x.TSet
	}
	return nil
}

type TsetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Alpha         []byte                 `protobuf:"bytes,2,opt,name=alpha,proto3" json:"alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsetValue) Reset() {
	*x = TsetValue{}
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsetValue) ProtoMessage() {}

func (x *TsetValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsetValue.ProtoReflect.Descriptor instead.
func (*TsetValue) Descriptor() ([]byte, []int) {
	return file_pkg_ODXT_proto_odxt_proto_rawDescGZIP(), []int{1}
}

func (x *TsetValue) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *TsetValue) GetAlpha() []byte {
	if x != nil {
		return x.Alpha
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ODXT_proto_odxt_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StokenList    []string               `protobuf:"bytes,1,rep,name=stoken_list,json=stokenList,proto3" json:"stoken_list,omitempty"`
	XtokenLists   []*XtokenList_2D       `protobuf:"bytes,2,rep,name=xtoken_lists,json=xtokenLists,proto3" json:"xtoken_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ODXT_proto_odxt_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetStokenList() []string {
	if x != nil {
		return x.StokenList
	}
	return nil
}

func (x *SearchRequest) GetXtokenLists() []*XtokenList_2D {
	if x != nil {
		return x.XtokenLists
	}
	return nil
}

type XtokenList_2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XtokenList    [][]byte               `protobuf:"bytes,1,rep,name=xtoken_list,json=xtokenList,proto3" json:"xtoken_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XtokenList_2D) Reset() {
	*x = XtokenList_2D{}
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XtokenList_2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XtokenList_2D) ProtoMessage() {}

func (x *XtokenList_2D) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XtokenList_2D.ProtoReflect.Descriptor instead.
func (*XtokenList_2D) Descriptor() ([]byte, []int) {
	return file_pkg_ODXT_proto_odxt_proto_rawDescGZIP(), []int{4}
}

func (x *XtokenList_2D) GetXtokenList() [][]byte {
	if x != nil {
		return x.XtokenList
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeopList      []*SEOp                `protobuf:"bytes,1,rep,name=seop_list,json=seopList,proto3" json:"seop_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ODXT_proto_odxt_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetSeopList() []*SEOp {
	if x != nil {
		return x.SeopList
	}
	return nil
}

type SEOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	J             int64                  `protobuf:"varint,1,opt,name=j,proto3" json:"j,omitempty"`
	Sval          string                 `protobuf:"bytes,2,opt,name=sval,proto3" json:"sval,omitempty"`
	Cnt           int64                  `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SEOp) Reset() {
	*x = SEOp{}
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SEOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEOp) ProtoMessage() {}

func (x *SEOp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ODXT_proto_odxt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEOp.ProtoReflect.Descriptor instead.
func (*SEOp) Descriptor() ([]byte, []int) {
	return file_pkg_ODXT_proto_odxt_proto_rawDescGZIP(), []int{6}
}

func (x *SEOp) GetJ() int64 {
	if x != nil {
		return x.J
	}
	return 0
}

func (x *SEOp) GetSval() string {
	if x != nil {
		return x.Sval
	}
	return ""
}

func (x *SEOp) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

var File_pkg_ODXT_proto_odxt_proto protoreflect.FileDescriptor

var file_pkg_ODXT_proto_odxt_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x4f, 0x44, 0x58, 0x54, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6f, 0x64, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xfe, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x78, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x58, 0x53, 0x65, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x78, 0x53, 0x65, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x74, 0x5f, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54,
	0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x53, 0x65, 0x74, 0x1a, 0x37,
	0x0a, 0x09, 0x58, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x4a, 0x0a, 0x09, 0x54, 0x53, 0x65, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x73,
	0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x34, 0x0a, 0x0a, 0x74, 0x73, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x22, 0x2a, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x6a, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x78, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x32, 0x44, 0x52, 0x0b, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x73, 0x22, 0x31, 0x0a, 0x0e, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x32, 0x44, 0x12, 0x1f, 0x0a, 0x0b, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x65, 0x6f, 0x70, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x45, 0x4f, 0x70, 0x52, 0x08, 0x73, 0x65, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x3a, 0x0a, 0x04, 0x53, 0x45, 0x4f, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x6a, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x01, 0x6a, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x76, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x76, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x6e, 0x74, 0x32, 0x81, 0x01, 0x0a,
	0x0b, 0x4f, 0x44, 0x58, 0x54, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x37, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67, 0x2f, 0x4f, 0x44, 0x58, 0x54, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_ODXT_proto_odxt_proto_rawDescOnce sync.Once
	file_pkg_ODXT_proto_odxt_proto_rawDescData []byte
)

func file_pkg_ODXT_proto_odxt_proto_rawDescGZIP() []byte {
	file_pkg_ODXT_proto_odxt_proto_rawDescOnce.Do(func() {
		file_pkg_ODXT_proto_odxt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ODXT_proto_odxt_proto_rawDesc), len(file_pkg_ODXT_proto_odxt_proto_rawDesc)))
	})
	return file_pkg_ODXT_proto_odxt_proto_rawDescData
}

var file_pkg_ODXT_proto_odxt_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_ODXT_proto_odxt_proto_goTypes = []any{
	(*UpdateRequest)(nil),  // 0: proto.UpdateRequest
	(*TsetValue)(nil),      // 1: proto.tset_value
	(*UpdateResponse)(nil), // 2: proto.UpdateResponse
	(*SearchRequest)(nil),  // 3: proto.SearchRequest
	(*XtokenList_2D)(nil),  // 4: proto.xtoken_list_2D
	(*SearchResponse)(nil), // 5: proto.SearchResponse
	(*SEOp)(nil),           // 6: proto.SEOp
	nil,                    // 7: proto.UpdateRequest.XSetEntry
	nil,                    // 8: proto.UpdateRequest.TSetEntry
}
var file_pkg_ODXT_proto_odxt_proto_depIdxs = []int32{
	7, // 0: proto.UpdateRequest.x_set:type_name -> proto.UpdateRequest.XSetEntry
	8, // 1: proto.UpdateRequest.t_set:type_name -> proto.UpdateRequest.TSetEntry
	4, // 2: proto.SearchRequest.xtoken_lists:type_name -> proto.xtoken_list_2D
	6, // 3: proto.SearchResponse.seop_list:type_name -> proto.SEOp
	1, // 4: proto.UpdateRequest.TSetEntry.value:type_name -> proto.tset_value
	0, // 5: proto.ODXTService.Update:input_type -> proto.UpdateRequest
	3, // 6: proto.ODXTService.Search:input_type -> proto.SearchRequest
	2, // 7: proto.ODXTService.Update:output_type -> proto.UpdateResponse
	5, // 8: proto.ODXTService.Search:output_type -> proto.SearchResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_ODXT_proto_odxt_proto_init() }
func file_pkg_ODXT_proto_odxt_proto_init() {
	if File_pkg_ODXT_proto_odxt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ODXT_proto_odxt_proto_rawDesc), len(file_pkg_ODXT_proto_odxt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ODXT_proto_odxt_proto_goTypes,
		DependencyIndexes: file_pkg_ODXT_proto_odxt_proto_depIdxs,
		MessageInfos:      file_pkg_ODXT_proto_odxt_proto_msgTypes,
	}.Build()
	File_pkg_ODXT_proto_odxt_proto = out.File
	file_pkg_ODXT_proto_odxt_proto_goTypes = nil
	file_pkg_ODXT_proto_odxt_proto_depIdxs = nil
}
