// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: pkg/FDXT/proto/fdxt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CDBXtag       map[string]string      `protobuf:"bytes,1,rep,name=CDBXtag,proto3" json:"CDBXtag,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CDBTset       map[string]*TsetValue  `protobuf:"bytes,2,rep,name=CDBTset,proto3" json:"CDBTset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetCDBXtag() map[string]string {
	if x != nil {
		return x.CDBXtag
	}
	return nil
}

func (x *UpdateRequest) GetCDBTset() map[string]*TsetValue {
	if x != nil {
		return x.CDBTset
	}
	return nil
}

type TsetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Alpha         []byte                 `protobuf:"bytes,2,opt,name=alpha,proto3" json:"alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsetValue) Reset() {
	*x = TsetValue{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsetValue) ProtoMessage() {}

func (x *TsetValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsetValue.ProtoReflect.Descriptor instead.
func (*TsetValue) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{1}
}

func (x *TsetValue) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *TsetValue) GetAlpha() []byte {
	if x != nil {
		return x.Alpha
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TklList       []*TKL                 `protobuf:"bytes,1,rep,name=tkl_list,json=tklList,proto3" json:"tkl_list,omitempty"`
	StklList      []string               `protobuf:"bytes,2,rep,name=stkl_list,json=stklList,proto3" json:"stkl_list,omitempty"`
	XtokenLists   []*XtokenList_2D       `protobuf:"bytes,3,rep,name=xtoken_lists,json=xtokenLists,proto3" json:"xtoken_lists,omitempty"`
	N             int64                  `protobuf:"varint,4,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetTklList() []*TKL {
	if x != nil {
		return x.TklList
	}
	return nil
}

func (x *SearchRequest) GetStklList() []string {
	if x != nil {
		return x.StklList
	}
	return nil
}

func (x *SearchRequest) GetXtokenLists() []*XtokenList_2D {
	if x != nil {
		return x.XtokenLists
	}
	return nil
}

func (x *SearchRequest) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

type TKL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L             string                 `protobuf:"bytes,1,opt,name=l,proto3" json:"l,omitempty"`
	T             string                 `protobuf:"bytes,2,opt,name=t,proto3" json:"t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TKL) Reset() {
	*x = TKL{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TKL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TKL) ProtoMessage() {}

func (x *TKL) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TKL.ProtoReflect.Descriptor instead.
func (*TKL) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{4}
}

func (x *TKL) GetL() string {
	if x != nil {
		return x.L
	}
	return ""
}

func (x *TKL) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

type XtokenList_2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XtokenList    [][]byte               `protobuf:"bytes,1,rep,name=xtoken_list,json=xtokenList,proto3" json:"xtoken_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XtokenList_2D) Reset() {
	*x = XtokenList_2D{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XtokenList_2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XtokenList_2D) ProtoMessage() {}

func (x *XtokenList_2D) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XtokenList_2D.ProtoReflect.Descriptor instead.
func (*XtokenList_2D) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{5}
}

func (x *XtokenList_2D) GetXtokenList() [][]byte {
	if x != nil {
		return x.XtokenList
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResList       []*RES                 `protobuf:"bytes,1,rep,name=res_list,json=resList,proto3" json:"res_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponse) GetResList() []*RES {
	if x != nil {
		return x.ResList
	}
	return nil
}

type RES struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sval          string                 `protobuf:"bytes,1,opt,name=sval,proto3" json:"sval,omitempty"`
	Cnt           int64                  `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RES) Reset() {
	*x = RES{}
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RES) ProtoMessage() {}

func (x *RES) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_FDXT_proto_fdxt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RES.ProtoReflect.Descriptor instead.
func (*RES) Descriptor() ([]byte, []int) {
	return file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP(), []int{7}
}

func (x *RES) GetSval() string {
	if x != nil {
		return x.Sval
	}
	return ""
}

func (x *RES) GetCnt() int64 {
	if x != nil {
		return x.Cnt
	}
	return 0
}

var File_pkg_FDXT_proto_fdxt_proto protoreflect.FileDescriptor

var file_pkg_FDXT_proto_fdxt_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x46, 0x44, 0x58, 0x54, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x66, 0x64, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x94, 0x02, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x07, 0x43, 0x44, 0x42, 0x58, 0x74, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x44, 0x42, 0x58,
	0x74, 0x61, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x43, 0x44, 0x42, 0x58, 0x74, 0x61,
	0x67, 0x12, 0x3b, 0x0a, 0x07, 0x43, 0x44, 0x42, 0x54, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x44, 0x42, 0x54, 0x73, 0x65, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x43, 0x44, 0x42, 0x54, 0x73, 0x65, 0x74, 0x1a, 0x3a,
	0x0a, 0x0c, 0x43, 0x44, 0x42, 0x58, 0x74, 0x61, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x4d, 0x0a, 0x0c, 0x43, 0x44,
	0x42, 0x54, 0x73, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x73, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x34, 0x0a, 0x0a, 0x74, 0x73, 0x65,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x22,
	0x2a, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x0d,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x08, 0x74, 0x6b, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4b, 0x4c, 0x52, 0x07, 0x74, 0x6b, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6b, 0x6c, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x6b, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x38, 0x0a, 0x0c, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x32, 0x44, 0x52, 0x0b,
	0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x22, 0x21, 0x0a, 0x03, 0x54, 0x4b, 0x4c,
	0x12, 0x0c, 0x0a, 0x01, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x6c, 0x12, 0x0c,
	0x0a, 0x01, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x74, 0x22, 0x31, 0x0a, 0x0e,
	0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x32, 0x44, 0x12, 0x1f,
	0x0a, 0x0b, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0a, 0x78, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x37, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x45, 0x53, 0x52,
	0x07, 0x72, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x03, 0x52, 0x45, 0x53, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x76, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x63, 0x6e, 0x74, 0x32, 0x81, 0x01, 0x0a, 0x0b, 0x46, 0x44, 0x58, 0x54, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x12, 0x37, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67,
	0x2f, 0x46, 0x44, 0x58, 0x54, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_pkg_FDXT_proto_fdxt_proto_rawDescOnce sync.Once
	file_pkg_FDXT_proto_fdxt_proto_rawDescData []byte
)

func file_pkg_FDXT_proto_fdxt_proto_rawDescGZIP() []byte {
	file_pkg_FDXT_proto_fdxt_proto_rawDescOnce.Do(func() {
		file_pkg_FDXT_proto_fdxt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_FDXT_proto_fdxt_proto_rawDesc), len(file_pkg_FDXT_proto_fdxt_proto_rawDesc)))
	})
	return file_pkg_FDXT_proto_fdxt_proto_rawDescData
}

var file_pkg_FDXT_proto_fdxt_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_FDXT_proto_fdxt_proto_goTypes = []any{
	(*UpdateRequest)(nil),  // 0: proto.UpdateRequest
	(*TsetValue)(nil),      // 1: proto.tset_value
	(*UpdateResponse)(nil), // 2: proto.UpdateResponse
	(*SearchRequest)(nil),  // 3: proto.SearchRequest
	(*TKL)(nil),            // 4: proto.TKL
	(*XtokenList_2D)(nil),  // 5: proto.xtoken_list_2D
	(*SearchResponse)(nil), // 6: proto.SearchResponse
	(*RES)(nil),            // 7: proto.RES
	nil,                    // 8: proto.UpdateRequest.CDBXtagEntry
	nil,                    // 9: proto.UpdateRequest.CDBTsetEntry
}
var file_pkg_FDXT_proto_fdxt_proto_depIdxs = []int32{
	8, // 0: proto.UpdateRequest.CDBXtag:type_name -> proto.UpdateRequest.CDBXtagEntry
	9, // 1: proto.UpdateRequest.CDBTset:type_name -> proto.UpdateRequest.CDBTsetEntry
	4, // 2: proto.SearchRequest.tkl_list:type_name -> proto.TKL
	5, // 3: proto.SearchRequest.xtoken_lists:type_name -> proto.xtoken_list_2D
	7, // 4: proto.SearchResponse.res_list:type_name -> proto.RES
	1, // 5: proto.UpdateRequest.CDBTsetEntry.value:type_name -> proto.tset_value
	0, // 6: proto.FDXTService.Update:input_type -> proto.UpdateRequest
	3, // 7: proto.FDXTService.Search:input_type -> proto.SearchRequest
	2, // 8: proto.FDXTService.Update:output_type -> proto.UpdateResponse
	6, // 9: proto.FDXTService.Search:output_type -> proto.SearchResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_FDXT_proto_fdxt_proto_init() }
func file_pkg_FDXT_proto_fdxt_proto_init() {
	if File_pkg_FDXT_proto_fdxt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_FDXT_proto_fdxt_proto_rawDesc), len(file_pkg_FDXT_proto_fdxt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_FDXT_proto_fdxt_proto_goTypes,
		DependencyIndexes: file_pkg_FDXT_proto_fdxt_proto_depIdxs,
		MessageInfos:      file_pkg_FDXT_proto_fdxt_proto_msgTypes,
	}.Build()
	File_pkg_FDXT_proto_fdxt_proto = out.File
	file_pkg_FDXT_proto_fdxt_proto_goTypes = nil
	file_pkg_FDXT_proto_fdxt_proto_depIdxs = nil
}
