// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/HDXT/proto/hdxt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_ADD       Operation = 0
	Operation_EDIT      Operation = 1
	Operation_EDIT_PLUS Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "ADD",
		1: "EDIT",
		2: "EDIT_PLUS",
	}
	Operation_value = map[string]int32{
		"ADD":       0,
		"EDIT":      1,
		"EDIT_PLUS": 2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_HDXT_proto_hdxt_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_pkg_HDXT_proto_hdxt_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{0}
}

type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MitraCiphers  map[string]string      `protobuf:"bytes,1,rep,name=mitra_ciphers,json=mitraCiphers,proto3" json:"mitra_ciphers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AuhmeCiphers  map[string]string      `protobuf:"bytes,2,rep,name=auhme_ciphers,json=auhmeCiphers,proto3" json:"auhme_ciphers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{0}
}

func (x *SetupRequest) GetMitraCiphers() map[string]string {
	if x != nil {
		return x.MitraCiphers
	}
	return nil
}

func (x *SetupRequest) GetAuhmeCiphers() map[string]string {
	if x != nil {
		return x.AuhmeCiphers
	}
	return nil
}

type SetupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupResponse) Reset() {
	*x = SetupResponse{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponse) ProtoMessage() {}

func (x *SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponse.ProtoReflect.Descriptor instead.
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{1}
}

func (x *SetupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateTokens  []*UTok                `protobuf:"bytes,1,rep,name=update_tokens,json=updateTokens,proto3" json:"update_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetUpdateTokens() []*UTok {
	if x != nil {
		return x.UpdateTokens
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchOneKeywordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trapdoors     []string               `protobuf:"bytes,1,rep,name=trapdoors,proto3" json:"trapdoors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOneKeywordRequest) Reset() {
	*x = SearchOneKeywordRequest{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOneKeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOneKeywordRequest) ProtoMessage() {}

func (x *SearchOneKeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOneKeywordRequest.ProtoReflect.Descriptor instead.
func (*SearchOneKeywordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{4}
}

func (x *SearchOneKeywordRequest) GetTrapdoors() []string {
	if x != nil {
		return x.Trapdoors
	}
	return nil
}

type SearchOneKeywordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedIds  []string               `protobuf:"bytes,1,rep,name=encrypted_ids,json=encryptedIds,proto3" json:"encrypted_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOneKeywordResponse) Reset() {
	*x = SearchOneKeywordResponse{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOneKeywordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOneKeywordResponse) ProtoMessage() {}

func (x *SearchOneKeywordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOneKeywordResponse.ProtoReflect.Descriptor instead.
func (*SearchOneKeywordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{5}
}

func (x *SearchOneKeywordResponse) GetEncryptedIds() []string {
	if x != nil {
		return x.EncryptedIds
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DkList        []*DK                  `protobuf:"bytes,1,rep,name=dk_list,json=dkList,proto3" json:"dk_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetDkList() []*DK {
	if x != nil {
		return x.DkList
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosList       []int32                `protobuf:"varint,1,rep,packed,name=pos_list,json=posList,proto3" json:"pos_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetPosList() []int32 {
	if x != nil {
		return x.PosList
	}
	return nil
}

type UTok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tok           map[string]string      `protobuf:"bytes,1,rep,name=tok,proto3" json:"tok,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Op            Operation              `protobuf:"varint,2,opt,name=op,proto3,enum=proto.Operation" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTok) Reset() {
	*x = UTok{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTok) ProtoMessage() {}

func (x *UTok) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTok.ProtoReflect.Descriptor instead.
func (*UTok) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{8}
}

func (x *UTok) GetTok() map[string]string {
	if x != nil {
		return x.Tok
	}
	return nil
}

func (x *UTok) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_ADD
}

type DK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L             []string               `protobuf:"bytes,1,rep,name=L,proto3" json:"L,omitempty"`
	R             string                 `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	D             string                 `protobuf:"bytes,3,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DK) Reset() {
	*x = DK{}
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DK) ProtoMessage() {}

func (x *DK) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_HDXT_proto_hdxt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DK.ProtoReflect.Descriptor instead.
func (*DK) Descriptor() ([]byte, []int) {
	return file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP(), []int{9}
}

func (x *DK) GetL() []string {
	if x != nil {
		return x.L
	}
	return nil
}

func (x *DK) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *DK) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

var File_pkg_HDXT_proto_hdxt_proto protoreflect.FileDescriptor

const file_pkg_HDXT_proto_hdxt_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/HDXT/proto/hdxt.proto\x12\x05proto\"\xa8\x02\n" +
	"\fSetupRequest\x12J\n" +
	"\rmitra_ciphers\x18\x01 \x03(\v2%.proto.SetupRequest.MitraCiphersEntryR\fmitraCiphers\x12J\n" +
	"\rauhme_ciphers\x18\x02 \x03(\v2%.proto.SetupRequest.AuhmeCiphersEntryR\fauhmeCiphers\x1a?\n" +
	"\x11MitraCiphersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11AuhmeCiphersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\rSetupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\rUpdateRequest\x120\n" +
	"\rupdate_tokens\x18\x01 \x03(\v2\v.proto.UTokR\fupdateTokens\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x17SearchOneKeywordRequest\x12\x1c\n" +
	"\ttrapdoors\x18\x01 \x03(\tR\ttrapdoors\"?\n" +
	"\x18SearchOneKeywordResponse\x12#\n" +
	"\rencrypted_ids\x18\x01 \x03(\tR\fencryptedIds\"3\n" +
	"\rSearchRequest\x12\"\n" +
	"\adk_list\x18\x01 \x03(\v2\t.proto.DKR\x06dkList\"+\n" +
	"\x0eSearchResponse\x12\x19\n" +
	"\bpos_list\x18\x01 \x03(\x05R\aposList\"\x88\x01\n" +
	"\x04UTok\x12&\n" +
	"\x03tok\x18\x01 \x03(\v2\x14.proto.UTok.TokEntryR\x03tok\x12 \n" +
	"\x02op\x18\x02 \x01(\x0e2\x10.proto.OperationR\x02op\x1a6\n" +
	"\bTokEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x02DK\x12\f\n" +
	"\x01L\x18\x01 \x03(\tR\x01L\x12\f\n" +
	"\x01r\x18\x02 \x01(\tR\x01r\x12\f\n" +
	"\x01d\x18\x03 \x01(\tR\x01d*-\n" +
	"\tOperation\x12\a\n" +
	"\x03ADD\x10\x00\x12\b\n" +
	"\x04EDIT\x10\x01\x12\r\n" +
	"\tEDIT_PLUS\x10\x022\x8e\x02\n" +
	"\vHDXTService\x126\n" +
	"\x05Setup\x12\x13.proto.SetupRequest\x1a\x14.proto.SetupResponse\"\x00(\x01\x127\n" +
	"\x06Update\x12\x14.proto.UpdateRequest\x1a\x15.proto.UpdateResponse\"\x00\x12U\n" +
	"\x10SearchOneKeyword\x12\x1e.proto.SearchOneKeywordRequest\x1a\x1f.proto.SearchOneKeywordResponse\"\x00\x127\n" +
	"\x06Search\x12\x14.proto.SearchRequest\x1a\x15.proto.SearchResponse\"\x00B\x10Z\x0epkg/HDXT/protob\x06proto3"

var (
	file_pkg_HDXT_proto_hdxt_proto_rawDescOnce sync.Once
	file_pkg_HDXT_proto_hdxt_proto_rawDescData []byte
)

func file_pkg_HDXT_proto_hdxt_proto_rawDescGZIP() []byte {
	file_pkg_HDXT_proto_hdxt_proto_rawDescOnce.Do(func() {
		file_pkg_HDXT_proto_hdxt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_HDXT_proto_hdxt_proto_rawDesc), len(file_pkg_HDXT_proto_hdxt_proto_rawDesc)))
	})
	return file_pkg_HDXT_proto_hdxt_proto_rawDescData
}

var file_pkg_HDXT_proto_hdxt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_HDXT_proto_hdxt_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_HDXT_proto_hdxt_proto_goTypes = []any{
	(Operation)(0),                   // 0: proto.Operation
	(*SetupRequest)(nil),             // 1: proto.SetupRequest
	(*SetupResponse)(nil),            // 2: proto.SetupResponse
	(*UpdateRequest)(nil),            // 3: proto.UpdateRequest
	(*UpdateResponse)(nil),           // 4: proto.UpdateResponse
	(*SearchOneKeywordRequest)(nil),  // 5: proto.SearchOneKeywordRequest
	(*SearchOneKeywordResponse)(nil), // 6: proto.SearchOneKeywordResponse
	(*SearchRequest)(nil),            // 7: proto.SearchRequest
	(*SearchResponse)(nil),           // 8: proto.SearchResponse
	(*UTok)(nil),                     // 9: proto.UTok
	(*DK)(nil),                       // 10: proto.DK
	nil,                              // 11: proto.SetupRequest.MitraCiphersEntry
	nil,                              // 12: proto.SetupRequest.AuhmeCiphersEntry
	nil,                              // 13: proto.UTok.TokEntry
}
var file_pkg_HDXT_proto_hdxt_proto_depIdxs = []int32{
	11, // 0: proto.SetupRequest.mitra_ciphers:type_name -> proto.SetupRequest.MitraCiphersEntry
	12, // 1: proto.SetupRequest.auhme_ciphers:type_name -> proto.SetupRequest.AuhmeCiphersEntry
	9,  // 2: proto.UpdateRequest.update_tokens:type_name -> proto.UTok
	10, // 3: proto.SearchRequest.dk_list:type_name -> proto.DK
	13, // 4: proto.UTok.tok:type_name -> proto.UTok.TokEntry
	0,  // 5: proto.UTok.op:type_name -> proto.Operation
	1,  // 6: proto.HDXTService.Setup:input_type -> proto.SetupRequest
	3,  // 7: proto.HDXTService.Update:input_type -> proto.UpdateRequest
	5,  // 8: proto.HDXTService.SearchOneKeyword:input_type -> proto.SearchOneKeywordRequest
	7,  // 9: proto.HDXTService.Search:input_type -> proto.SearchRequest
	2,  // 10: proto.HDXTService.Setup:output_type -> proto.SetupResponse
	4,  // 11: proto.HDXTService.Update:output_type -> proto.UpdateResponse
	6,  // 12: proto.HDXTService.SearchOneKeyword:output_type -> proto.SearchOneKeywordResponse
	8,  // 13: proto.HDXTService.Search:output_type -> proto.SearchResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_HDXT_proto_hdxt_proto_init() }
func file_pkg_HDXT_proto_hdxt_proto_init() {
	if File_pkg_HDXT_proto_hdxt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_HDXT_proto_hdxt_proto_rawDesc), len(file_pkg_HDXT_proto_hdxt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_HDXT_proto_hdxt_proto_goTypes,
		DependencyIndexes: file_pkg_HDXT_proto_hdxt_proto_depIdxs,
		EnumInfos:         file_pkg_HDXT_proto_hdxt_proto_enumTypes,
		MessageInfos:      file_pkg_HDXT_proto_hdxt_proto_msgTypes,
	}.Build()
	File_pkg_HDXT_proto_hdxt_proto = out.File
	file_pkg_HDXT_proto_hdxt_proto_goTypes = nil
	file_pkg_HDXT_proto_hdxt_proto_depIdxs = nil
}
