// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/HDXT/proto/hdxt.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HDXTService_Setup_FullMethodName            = "/proto.HDXTService/Setup"
	HDXTService_Update_FullMethodName           = "/proto.HDXTService/Update"
	HDXTService_SearchOneKeyword_FullMethodName = "/proto.HDXTService/SearchOneKeyword"
	HDXTService_Search_FullMethodName           = "/proto.HDXTService/Search"
)

// HDXTServiceClient is the client API for HDXTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HDXTServiceClient interface {
	Setup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SetupRequest, SetupResponse], error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	SearchOneKeyword(ctx context.Context, in *SearchOneKeywordRequest, opts ...grpc.CallOption) (*SearchOneKeywordResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type hDXTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHDXTServiceClient(cc grpc.ClientConnInterface) HDXTServiceClient {
	return &hDXTServiceClient{cc}
}

func (c *hDXTServiceClient) Setup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SetupRequest, SetupResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HDXTService_ServiceDesc.Streams[0], HDXTService_Setup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetupRequest, SetupResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HDXTService_SetupClient = grpc.ClientStreamingClient[SetupRequest, SetupResponse]

func (c *hDXTServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, HDXTService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hDXTServiceClient) SearchOneKeyword(ctx context.Context, in *SearchOneKeywordRequest, opts ...grpc.CallOption) (*SearchOneKeywordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchOneKeywordResponse)
	err := c.cc.Invoke(ctx, HDXTService_SearchOneKeyword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hDXTServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, HDXTService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HDXTServiceServer is the server API for HDXTService service.
// All implementations must embed UnimplementedHDXTServiceServer
// for forward compatibility.
type HDXTServiceServer interface {
	Setup(grpc.ClientStreamingServer[SetupRequest, SetupResponse]) error
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	SearchOneKeyword(context.Context, *SearchOneKeywordRequest) (*SearchOneKeywordResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedHDXTServiceServer()
}

// UnimplementedHDXTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHDXTServiceServer struct{}

func (UnimplementedHDXTServiceServer) Setup(grpc.ClientStreamingServer[SetupRequest, SetupResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (UnimplementedHDXTServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedHDXTServiceServer) SearchOneKeyword(context.Context, *SearchOneKeywordRequest) (*SearchOneKeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchOneKeyword not implemented")
}
func (UnimplementedHDXTServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedHDXTServiceServer) mustEmbedUnimplementedHDXTServiceServer() {}
func (UnimplementedHDXTServiceServer) testEmbeddedByValue()                     {}

// UnsafeHDXTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HDXTServiceServer will
// result in compilation errors.
type UnsafeHDXTServiceServer interface {
	mustEmbedUnimplementedHDXTServiceServer()
}

func RegisterHDXTServiceServer(s grpc.ServiceRegistrar, srv HDXTServiceServer) {
	// If the following call pancis, it indicates UnimplementedHDXTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HDXTService_ServiceDesc, srv)
}

func _HDXTService_Setup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HDXTServiceServer).Setup(&grpc.GenericServerStream[SetupRequest, SetupResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HDXTService_SetupServer = grpc.ClientStreamingServer[SetupRequest, SetupResponse]

func _HDXTService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HDXTServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HDXTService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HDXTServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HDXTService_SearchOneKeyword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOneKeywordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HDXTServiceServer).SearchOneKeyword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HDXTService_SearchOneKeyword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HDXTServiceServer).SearchOneKeyword(ctx, req.(*SearchOneKeywordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HDXTService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HDXTServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HDXTService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HDXTServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HDXTService_ServiceDesc is the grpc.ServiceDesc for HDXTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HDXTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HDXTService",
	HandlerType: (*HDXTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _HDXTService_Update_Handler,
		},
		{
			MethodName: "SearchOneKeyword",
			Handler:    _HDXTService_SearchOneKeyword_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _HDXTService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Setup",
			Handler:       _HDXTService_Setup_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/HDXT/proto/hdxt.proto",
}
