// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/SDSSE-CQ/proto/sdssecq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tset          map[string]string      `protobuf:"bytes,1,rep,name=tset,proto3" json:"tset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Xset          map[string]string      `protobuf:"bytes,2,rep,name=xset,proto3" json:"xset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescGZIP(), []int{0}
}

func (x *SetupRequest) GetTset() map[string]string {
	if x != nil {
		return x.Tset
	}
	return nil
}

func (x *SetupRequest) GetXset() map[string]string {
	if x != nil {
		return x.Xset
	}
	return nil
}

type SetupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupResponse) Reset() {
	*x = SetupResponse{}
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponse) ProtoMessage() {}

func (x *SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponse.ProtoReflect.Descriptor instead.
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescGZIP(), []int{1}
}

func (x *SetupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            int64                  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Tval          string                 `protobuf:"bytes,4,opt,name=tval,proto3" json:"tval,omitempty"`
	Xval          string                 `protobuf:"bytes,5,opt,name=xval,proto3" json:"xval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *UpdateRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetTval() string {
	if x != nil {
		return x.Tval
	}
	return ""
}

func (x *UpdateRequest) GetXval() string {
	if x != nil {
		return x.Xval
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W1            string                 `protobuf:"bytes,1,opt,name=w1,proto3" json:"w1,omitempty"`
	Keywords      []string               `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"` // keywords to search in XSet (excluding w1)
	XtokenLists   [][]byte               `protobuf:"bytes,3,rep,name=xtoken_lists,json=xtokenLists,proto3" json:"xtoken_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetW1() string {
	if x != nil {
		return x.W1
	}
	return ""
}

func (x *SearchRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SearchRequest) GetXtokenLists() [][]byte {
	if x != nil {
		return x.XtokenLists
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultList    []string               `protobuf:"bytes,1,rep,name=result_list,json=resultList,proto3" json:"result_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetResultList() []string {
	if x != nil {
		return x.ResultList
	}
	return nil
}

var File_pkg_SDSSE_CQ_proto_sdssecq_proto protoreflect.FileDescriptor

const file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDesc = "" +
	"\n" +
	" pkg/SDSSE-CQ/proto/sdssecq.proto\x12\x05proto\"\xe6\x01\n" +
	"\fSetupRequest\x121\n" +
	"\x04tset\x18\x01 \x03(\v2\x1d.proto.SetupRequest.TsetEntryR\x04tset\x121\n" +
	"\x04xset\x18\x02 \x03(\v2\x1d.proto.SetupRequest.XsetEntryR\x04xset\x1a7\n" +
	"\tTsetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tXsetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\rSetupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"q\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x03R\x02op\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04tval\x18\x04 \x01(\tR\x04tval\x12\x12\n" +
	"\x04xval\x18\x05 \x01(\tR\x04xval\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"^\n" +
	"\rSearchRequest\x12\x0e\n" +
	"\x02w1\x18\x01 \x01(\tR\x02w1\x12\x1a\n" +
	"\bkeywords\x18\x02 \x03(\tR\bkeywords\x12!\n" +
	"\fxtoken_lists\x18\x03 \x03(\fR\vxtokenLists\"1\n" +
	"\x0eSearchResponse\x12\x1f\n" +
	"\vresult_list\x18\x01 \x03(\tR\n" +
	"resultList2\xba\x01\n" +
	"\x0eSDSSEcqService\x126\n" +
	"\x05Setup\x12\x13.proto.SetupRequest\x1a\x14.proto.SetupResponse\"\x00(\x01\x127\n" +
	"\x06Update\x12\x14.proto.UpdateRequest\x1a\x15.proto.UpdateResponse\"\x00\x127\n" +
	"\x06Search\x12\x14.proto.SearchRequest\x1a\x15.proto.SearchResponse\"\x00B\x14Z\x12pkg/SDSSE-CQ/protob\x06proto3"

var (
	file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescOnce sync.Once
	file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescData []byte
)

func file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescGZIP() []byte {
	file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescOnce.Do(func() {
		file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDesc), len(file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDesc)))
	})
	return file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDescData
}

var file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_SDSSE_CQ_proto_sdssecq_proto_goTypes = []any{
	(*SetupRequest)(nil),   // 0: proto.SetupRequest
	(*SetupResponse)(nil),  // 1: proto.SetupResponse
	(*UpdateRequest)(nil),  // 2: proto.UpdateRequest
	(*UpdateResponse)(nil), // 3: proto.UpdateResponse
	(*SearchRequest)(nil),  // 4: proto.SearchRequest
	(*SearchResponse)(nil), // 5: proto.SearchResponse
	nil,                    // 6: proto.SetupRequest.TsetEntry
	nil,                    // 7: proto.SetupRequest.XsetEntry
}
var file_pkg_SDSSE_CQ_proto_sdssecq_proto_depIdxs = []int32{
	6, // 0: proto.SetupRequest.tset:type_name -> proto.SetupRequest.TsetEntry
	7, // 1: proto.SetupRequest.xset:type_name -> proto.SetupRequest.XsetEntry
	0, // 2: proto.SDSSEcqService.Setup:input_type -> proto.SetupRequest
	2, // 3: proto.SDSSEcqService.Update:input_type -> proto.UpdateRequest
	4, // 4: proto.SDSSEcqService.Search:input_type -> proto.SearchRequest
	1, // 5: proto.SDSSEcqService.Setup:output_type -> proto.SetupResponse
	3, // 6: proto.SDSSEcqService.Update:output_type -> proto.UpdateResponse
	5, // 7: proto.SDSSEcqService.Search:output_type -> proto.SearchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_SDSSE_CQ_proto_sdssecq_proto_init() }
func file_pkg_SDSSE_CQ_proto_sdssecq_proto_init() {
	if File_pkg_SDSSE_CQ_proto_sdssecq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDesc), len(file_pkg_SDSSE_CQ_proto_sdssecq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_SDSSE_CQ_proto_sdssecq_proto_goTypes,
		DependencyIndexes: file_pkg_SDSSE_CQ_proto_sdssecq_proto_depIdxs,
		MessageInfos:      file_pkg_SDSSE_CQ_proto_sdssecq_proto_msgTypes,
	}.Build()
	File_pkg_SDSSE_CQ_proto_sdssecq_proto = out.File
	file_pkg_SDSSE_CQ_proto_sdssecq_proto_goTypes = nil
	file_pkg_SDSSE_CQ_proto_sdssecq_proto_depIdxs = nil
}
