// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: pkg/SDSSE-CQ/proto/sdssecq.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SDSSEcqService_Setup_FullMethodName  = "/proto.SDSSEcqService/Setup"
	SDSSEcqService_Update_FullMethodName = "/proto.SDSSEcqService/Update"
	SDSSEcqService_Search_FullMethodName = "/proto.SDSSEcqService/Search"
)

// SDSSEcqServiceClient is the client API for SDSSEcqService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SDSSEcqServiceClient interface {
	Setup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SetupRequest, SetupResponse], error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type sDSSEcqServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSDSSEcqServiceClient(cc grpc.ClientConnInterface) SDSSEcqServiceClient {
	return &sDSSEcqServiceClient{cc}
}

func (c *sDSSEcqServiceClient) Setup(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SetupRequest, SetupResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SDSSEcqService_ServiceDesc.Streams[0], SDSSEcqService_Setup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetupRequest, SetupResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDSSEcqService_SetupClient = grpc.ClientStreamingClient[SetupRequest, SetupResponse]

func (c *sDSSEcqServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, SDSSEcqService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSSEcqServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SDSSEcqService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SDSSEcqServiceServer is the server API for SDSSEcqService service.
// All implementations must embed UnimplementedSDSSEcqServiceServer
// for forward compatibility.
type SDSSEcqServiceServer interface {
	Setup(grpc.ClientStreamingServer[SetupRequest, SetupResponse]) error
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedSDSSEcqServiceServer()
}

// UnimplementedSDSSEcqServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSDSSEcqServiceServer struct{}

func (UnimplementedSDSSEcqServiceServer) Setup(grpc.ClientStreamingServer[SetupRequest, SetupResponse]) error {
	return status.Error(codes.Unimplemented, "method Setup not implemented")
}
func (UnimplementedSDSSEcqServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSDSSEcqServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSDSSEcqServiceServer) mustEmbedUnimplementedSDSSEcqServiceServer() {}
func (UnimplementedSDSSEcqServiceServer) testEmbeddedByValue()                        {}

// UnsafeSDSSEcqServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SDSSEcqServiceServer will
// result in compilation errors.
type UnsafeSDSSEcqServiceServer interface {
	mustEmbedUnimplementedSDSSEcqServiceServer()
}

func RegisterSDSSEcqServiceServer(s grpc.ServiceRegistrar, srv SDSSEcqServiceServer) {
	// If the following call panics, it indicates UnimplementedSDSSEcqServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SDSSEcqService_ServiceDesc, srv)
}

func _SDSSEcqService_Setup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SDSSEcqServiceServer).Setup(&grpc.GenericServerStream[SetupRequest, SetupResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDSSEcqService_SetupServer = grpc.ClientStreamingServer[SetupRequest, SetupResponse]

func _SDSSEcqService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSSEcqServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSSEcqService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSSEcqServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSSEcqService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSSEcqServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSSEcqService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSSEcqServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SDSSEcqService_ServiceDesc is the grpc.ServiceDesc for SDSSEcqService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SDSSEcqService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SDSSEcqService",
	HandlerType: (*SDSSEcqServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _SDSSEcqService_Update_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _SDSSEcqService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Setup",
			Handler:       _SDSSEcqService_Setup_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/SDSSE-CQ/proto/sdssecq.proto",
}
