syntax = "proto3";

package proto;
option go_package = "pkg/SDSSE-CQ/proto";

service SDSSEcqService {
  rpc Setup(stream SetupRequest) returns (SetupResponse) {}
  rpc Update(UpdateRequest) returns (UpdateResponse) {}
  rpc Search(SearchRequest) returns (SearchResponse) {}
}

message SetupRequest {
  map<string, string> tset = 1;
  map<string, string> xset = 2;
}

message SetupResponse {
  bool success = 1;
}

message UpdateRequest {
  int64 op = 1;
  string keyword = 2;
  string id = 3;
  string tval = 4;
  string xval = 5;
}

message UpdateResponse {
  bool success = 1;
}

message SearchRequest {
  string w1 = 1;
  repeated string keywords = 2;  // keywords to search in XSet (excluding w1)
  repeated bytes xtoken_lists = 3;
}

message SearchResponse {
  repeated string result_list = 1;
}
